### ISSUE TITLE
Amazing script! Can this script be ported as an Expo.io App?

### ISSUE THREAD

**Issue by inglesuniversal** [insiderdev/qrcode#2]
Best regards!

**Comment by gaykov** [comment]
Hello @inglesuniversal!

It's possible to white this app as an Expo application, but it will require a few adjustments. For example, all the native libraries we installed should be imported from the Expo core (a few of them needs to be replaced, as the don't exist in Expo).

**Comment by inglesuniversal** [comment]
mmm.... thanks.... or ... is it really HARD to work on react native alone.... it takes for ever to compile and I guess you have to have not only x-code but android studio to make the final builds to export them to the app store and play store... doesn't it?

Is there a SHORTCUT? A way to create the react native scripts and then build them in the cloud like expo?

Honestly, for me that's the hardest part I've seen.... That's why I turn to Expo all the time... It's so simple... but it lacks a ton of libraries and features at this point.

I would appreciate any pointers you can provide me with.

Thanks so much!

**Comment by gaykov** [comment]
Nope, there're no shortcuts or anything. XCode, Android studios are tradeoffs for being able to write custom native code and use any native library that doesn't exist in expo.

I'm going to close this issue for now, but feel free to ask any questions here :)
