### ISSUE TITLE
android run error

### ISSUE THREAD

**Issue by xgqfrms** [insiderdev/qrcode#5]
# android run error

> java version bug ?

![image](https://user-images.githubusercontent.com/7291672/56857196-29962b00-699d-11e9-99dd-29a55154a13a.png)

**Comment by gaykov** [comment]
Hi @xgqfrms ! Looks like it's related to your environment, not the project. Have you seen this issue with a few tips that might be helpful for you https://github.com/facebook/react-native/issues/22487 ?

**Comment by xgqfrms** [comment]
@gaykov Thanks a lot.
