### ISSUE TITLE
Always No response(无响应）

### ISSUE THREAD

**Issue by NBInfo** [insiderdev/qrcode#6]
![Screenshot_20190901-001332](https://user-images.githubusercontent.com/17871089/64066641-53709000-cbd1-11e9-9644-185829b2c1b0.png)
![Screenshot from 2019-08-31 09-14-00](https://user-images.githubusercontent.com/17871089/64066642-579cad80-cbd1-11e9-9207-162e5221eea0.png)

**Comment by NBInfo** [comment]
Unable to run

**Comment by NBInfo** [comment]
解决了 不要在mware下运行

**Comment by gaykov** [comment]
Hi @NBInfo! Looks like this issue is related to your environment, not to the repo code. Can you please tell me if you are able to run any other React Native project on the same machine?

**Comment by NBInfo** [comment]
> 嗨@NBInfo！看起来这个问题与您的环境有关，而与回购代码无关。如果能在同一台机器上运行任何其他React Native项目，能否告诉我？

It is likely that the virtual machine ip address and the Android device ip are no longer on a network segment.

I am trying to build on a real linux pc
Perfect operation

**Comment by gaykov** [comment]
Ok, so I'm going to close the issue now. Feel free to reopen it if needed.
