### ISSUE TITLE
Android build failed-Unexpected format of Google App ID

### ISSUE THREAD

**Issue by nileshpandey3** [insiderdev/qrcode#7]
` Task :app:processDebugGoogleServices FAILED
Parsing json file: /Users/nileshpandey/Downloads/qrcode-master/android/app/google-services.json

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Unexpected format of Google App ID. Please follow instructions on https://firebase.google.com/ to get a config file that contains a valid Google App Id or update the plugin version if you believe your Google App Id [***REMOVED***] is correct.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
60 actionable tasks: 1 executed, 59 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by gaykov** [comment]
Have a look at the Firebase file here: https://github.com/insiderdev/qrcode/blob/master/android/app/google-services.json. It has invalid format with all the secrets removed. So you need to update this file with your project's Firebase credentials. We will update the readme with this instructions (#9)
